repos:
  - repo: local
    hooks:
      - id: nixfmt
        name: Format Nix files with nixfmt
        entry: nixfmt
        language: system
        files: '\.nix$'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
