#!/usr/bin/env bash
set -euo pipefail

readonly GREEN='\033[1;32m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m'

readonly NIX="/nix/var/nix/profiles/default/bin/nix"
readonly SYSTEM_TYPE="aarch64-darwin"
readonly FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

printf '%b\n' "${YELLOW}Starting build...${NC}"
system_path=$("${NIX}" build --no-link --print-out-paths ".#${FLAKE_SYSTEM}" "$@")

printf '%b\n' "${YELLOW}Switching to the new generation...${NC}"
# See https://github.com/nix-darwin/nix-darwin/issues/1457 on why we need sudo
sudo "${system_path}/sw/bin/darwin-rebuild" switch --flake ".#${SYSTEM_TYPE}" "$@"

printf '%b\n' "${GREEN}Switch complete.${NC}"
