#!/usr/bin/env bash
set -euo pipefail

readonly GREEN='\033[1;32m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m'

readonly NIX="/nix/var/nix/profiles/default/bin/nix"
readonly SYSTEM_TYPE="aarch64-darwin"
readonly FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

printf '%b\n' "${YELLOW}Starting build...${NC}"
"${NIX}" build --no-link --print-out-paths ".#${FLAKE_SYSTEM}" "$@"

printf '%b\n' "${GREEN}Build complete.${NC}"
